.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd DATE               \" DATE 
.Dt xkbgrowl 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm xkbgrowl,
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd A server to route X11 bell event to Growl.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl display Ar display   \" [-display display] 
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm xkbgrowl
starts the bell event routing server.
.P
The xkbgrowl program connects to the X11 server can retrieves bell events and routes
them to the Growl system. For each bell event, one Growl notification is 
generated. For each notification, the text is build from the name of the bell.
.P
Additionally, if a window is attached to the X11 bell event, the following information is retrieved:
.Bl -bullet
.It
Name of the window.
.It
Hostname of the X11 client.
.It
Window manager icon (used to build the Growl notification icon).
.It
Window manager icon mask (used to build the growl notification icon).
.El
.Sh ENVIRONMENT
.Bl -tag
.It Ev DISPLAY
The X11 display to use connect to, overriden with the -display parameter.
.El
.Sh EXAMPLE
.Bl -tag
.It Sending a notification from within an xterm:
xkbbell -nobeep -w $WINDOWID "Hello World"
.El
.Sh SEE ALSO 
.Xr xkbevd 1
.Xr xkbbell 1
.Sh HOMEPAGE
For more information, see https://code.google.com/p/xkbgrowl/
.Sh BUGS
.Bl -bullet
.It
If the growl system is not running, xkbgrowl will just exit with an error message.
.It
The NX client system interferes with X11 notification, so xkbgrowl does not work properly with NX.
.El
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner